# Generated by Django 5.1.1 on 2024-11-17 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='categogy',
            field=models.ManyToManyField(related_name='product', to='app.category'),
        ),
    ]
