# Generated by Django 5.1.1 on 2024-12-04 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_product_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='approved_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
