# Generated by Django 5.1.1 on 2024-12-05 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_order_approved_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Chưa duyệt'), ('approved', 'Đã duyệt'), ('canceled', 'Đã hủy')], default='pending', max_length=20),
        ),
    ]
